insert into public.directorates (code, name)
values
  ('administration_national_intl', 'Directorate of Administration (National & International)'),
  ('missions_evangelism', 'Directorate of Missions and Evangelism'),
  ('intercession_prayer', 'Directorate of Intercession and Prayer (under National Coordinator)'),
  ('discipleship_mentorship', 'Directorate of Discipleship and Mentorship'),
  ('ministerial_education_training', 'Directorate of Ministerial Education and Training'),
  ('music_governance_strategy', 'Directorate of Music, Governance, Strategy & Administration'),
  ('politics_governance', 'Directorate of Politics and Governance'),
  ('research_monitoring_eval', 'Directorate of Research, Monitoring, Evaluation & Mobilization'),
  ('finance_treasury_supply', 'Directorate of Finance, Treasury, Purchase & Supply'),
  ('audit_influence', 'Directorate Of Internal And External Audit Programs, Engagement & Influence'),
  ('programs_publicity', 'Directorate of Programs and Publicity'),
  ('inter_ministerial_services', 'Directorate of Inter-Ministerial Services'),
  ('women_affairs', 'Directorate of Women Affairs'),
  ('intl_affairs_partnership', 'Directorate of International Affairs, Partnership & Mission, People, Care & Social Impact'),
  ('youth_affairs_social', 'Directorate of Youth Affairs and Social Services'),
  ('hospitality_welfare_humanitarian', 'Directorate of Hospitality, Welfare & Humanitarian Affairs'),
  ('security_defense', 'Directorate of Security and Defense'),
  ('communication_transport_logistics', 'Directorate of Communication, Transport & Logistics'),
  ('health_services_infra', 'Directorate of Health Services Operations, Security & Infrastructure'),
  ('electricity_infrastructure_facilities', 'Directorate of Electricity, Infrastructure & Facility Maintenance'),
  ('education_schools', 'Directorate of Education and Schools'),
  ('child_evangelism_training', 'Directorate of Child Evangelism and Training')
on conflict (code) do update
set
  name = excluded.name,
  updated_at = now();

with unit_seed (code, directorate_code, name) as (
  values
    ('ad_u1', 'administration_national_intl', 'National administration office unit'),
    ('ad_u2', 'administration_national_intl', 'International administration office unit'),
    ('ad_u3', 'administration_national_intl', 'Human resource and personnel management unit'),
    ('ad_u4', 'administration_national_intl', 'Records, documentation and compliance unit'),
    ('me_u1', 'missions_evangelism', 'Street and Community Evangelism Unit'),
    ('me_u2', 'missions_evangelism', 'Missionary and rural outreach unit'),
    ('me_u3', 'missions_evangelism', 'Crusades and mass evangelism unit'),
    ('me_u4', 'missions_evangelism', 'Convert care and integration unit'),
    ('ip_u1', 'intercession_prayer', 'National prayer operations unit'),
    ('ip_u2', 'intercession_prayer', 'Intercessors network and mobilization unit'),
    ('ip_u3', 'intercession_prayer', 'Prayer bulletins and prophetic intelligence unit'),
    ('ip_u4', 'intercession_prayer', 'Fasting and consecration unit'),
    ('dm_u1', 'discipleship_mentorship', 'New converts and foundations unit'),
    ('dm_u2', 'discipleship_mentorship', 'Discipleship pathways and growth unit'),
    ('dm_u3', 'discipleship_mentorship', 'Mentorship and leadership development unit'),
    ('dm_u4', 'discipleship_mentorship', 'Cell groups and spiritual communities unit'),
    ('met_provost', 'ministerial_education_training', 'Provost: EBOMIM School of Ministry'),
    ('met_u1', 'ministerial_education_training', 'Curriculum and doctrinal development unit'),
    ('met_u2', 'ministerial_education_training', 'Missionary and field training unit'),
    ('met_u3', 'ministerial_education_training', 'Prayer and intercessory training unit'),
    ('met_u4', 'ministerial_education_training', 'Leadership, character, and ethics unit'),
    ('mgs_u1', 'music_governance_strategy', 'Worship and praise unit'),
    ('mgs_u2', 'music_governance_strategy', 'Choir and vocal training unit'),
    ('mgs_u3', 'music_governance_strategy', 'Instrument and band unit'),
    ('mgs_u4', 'music_governance_strategy', 'Music composition and content review unit'),
    ('pg_u1', 'politics_governance', 'Governance intelligence and policy research unit'),
    ('pg_u2', 'politics_governance', 'Kingdom leadership and public service preparations unit'),
    ('pg_u3', 'politics_governance', 'Civic engagement and voter education'),
    ('pg_u4', 'politics_governance', 'Advocacy, justice and public intervention unit'),
    ('rme_u1', 'research_monitoring_eval', 'Research and strategy development unit'),
    ('rme_u2', 'research_monitoring_eval', 'Monitoring and field compliance unit'),
    ('rme_u3', 'research_monitoring_eval', 'Evaluation and performance unit'),
    ('rme_u4', 'research_monitoring_eval', 'Mobilization and participation unit'),
    ('fts_u1', 'finance_treasury_supply', 'Finance and accounts unit'),
    ('fts_u2', 'finance_treasury_supply', 'Treasury and funds management unit'),
    ('fts_u3', 'finance_treasury_supply', 'Procurement and purchasing unit'),
    ('fts_u4', 'finance_treasury_supply', 'Stores, inventory and supply unit'),
    ('ai_u1', 'audit_influence', 'Financial accountability'),
    ('ai_u2', 'audit_influence', 'Administrative compliance'),
    ('ai_u3', 'audit_influence', 'Risk management'),
    ('ai_u4', 'audit_influence', 'Ethics and integrity'),
    ('pp_u1', 'programs_publicity', 'Program design and planning'),
    ('pp_u2', 'programs_publicity', 'Scheduling and calendar management unit'),
    ('pp_u3', 'programs_publicity', 'Publicity and announcement unit'),
    ('pp_u4', 'programs_publicity', 'Program monitoring and feedback unit'),
    ('ims_u1', 'inter_ministerial_services', 'Christian bodies liaison unit'),
    ('ims_u2', 'inter_ministerial_services', 'Partnership and collaboration unit'),
    ('ims_u3', 'inter_ministerial_services', 'Protocol and official representation unit'),
    ('ims_u4', 'inter_ministerial_services', 'Conflict resolution and advisory unit'),
    ('wa_u1', 'women_affairs', 'Women discipleship and spiritual growth'),
    ('wa_u2', 'women_affairs', 'Women leadership and capacity development unit'),
    ('wa_u3', 'women_affairs', 'Women welfare and family support unit'),
    ('wa_u4', 'women_affairs', 'Women mobilization and outreach unit'),
    ('iap_u1', 'intl_affairs_partnership', 'International missions and outreach unit'),
    ('iap_u2', 'intl_affairs_partnership', 'Global partnership and alliances unit'),
    ('iap_u3', 'intl_affairs_partnership', 'International branches and diaspora coordination unit'),
    ('iap_u4', 'intl_affairs_partnership', 'International protocol, compliance, and liaison unit'),
    ('yas_u1', 'youth_affairs_social', 'Youth discipleship and spiritual formation unit'),
    ('yas_u2', 'youth_affairs_social', 'Youth leadership and capacity development unit'),
    ('yas_u3', 'youth_affairs_social', 'Youth social services and empowerment unit'),
    ('yas_u4', 'youth_affairs_social', 'Youth mobilization and outreach unit'),
    ('hwh_u1', 'hospitality_welfare_humanitarian', 'Hospitality and guest services unit'),
    ('hwh_u2', 'hospitality_welfare_humanitarian', 'Staff members and welfare unit'),
    ('hwh_u3', 'hospitality_welfare_humanitarian', 'Humanitarian outreach and relief unit'),
    ('hwh_u4', 'hospitality_welfare_humanitarian', 'Volunteers and care support unit'),
    ('sd_u1', 'security_defense', 'VIP and leadership protection unit'),
    ('sd_u2', 'security_defense', 'Facility and infrastructure security unit'),
    ('sd_u3', 'security_defense', 'Programs and event security unit'),
    ('sd_u4', 'security_defense', 'Security intelligence and risk assessment unit'),
    ('ctl_u1', 'communication_transport_logistics', 'Media, ICT, digital communications unit'),
    ('ctl_u2', 'communication_transport_logistics', 'Sound, publication and printing unit'),
    ('ctl_u3', 'communication_transport_logistics', 'Transport and fleet management unit'),
    ('ctl_u4', 'communication_transport_logistics', 'Logistics and equipment support unit'),
    ('hsi_u1', 'health_services_infra', 'Clinical service and first aid unit'),
    ('hsi_u2', 'health_services_infra', 'Medical outreach and community health unit'),
    ('hsi_u3', 'health_services_infra', 'Preventive health and wellness education unit'),
    ('hsi_u4', 'health_services_infra', 'Medical logistics and compliance unit'),
    ('eif_u1', 'electricity_infrastructure_facilities', 'Electricity and power systems unit'),
    ('eif_u2', 'electricity_infrastructure_facilities', 'Infrastructure development and projects unit'),
    ('eif_u3', 'electricity_infrastructure_facilities', 'Facility maintenance and utilities unit'),
    ('eif_u4', 'electricity_infrastructure_facilities', 'Assets and equipment maintenance unit'),
    ('cet_u1', 'child_evangelism_training', 'Child evangelism and gospel outreach unit'),
    ('cet_u2', 'child_evangelism_training', 'Biblical instructions and curriculum unit'),
    ('cet_u3', 'child_evangelism_training', 'Character formation and life skill unit'),
    ('cet_u4', 'child_evangelism_training', 'Child safety, welfare and care unit')
)
insert into public.units (code, directorate_id, name)
select unit_seed.code, directorates.id, unit_seed.name
from unit_seed
join public.directorates on directorates.code = unit_seed.directorate_code
on conflict (code) do update
set
  directorate_id = excluded.directorate_id,
  name = excluded.name,
  updated_at = now();
